Dev/location test pr
san-ghun/webserv pull request #10
Opened 2024-07-26 10:44 UTC by miooo0o

Implemented the import of Config and Location classes and the creation of the correct response.
- resolve build errors due to circular dependency
- modularization of existing methods, logic refined in the meeting with @san-ghun 
- documentation
- Renamed/unified some methods (mostly in HttpResponse, StaticFileHandler files)
- Change `ext` in `mime-type` list  so that it does not contain `.`

tested:
```
http://localhost:8080/fruits/index.html    -------> OK (file opened)
http://localhost:8080/fruits/   ------------------> OK (index.html fetching)
http://localhost:8080/    ------------------------> OK (index.html fetching)
```

2024-07-26 21:00 UTC, san-ghun requested changes
Hey @miooo0o ,
thanks for you hard work.

I see some parts that need modification.
Please have look at my review and change those points.

Leave comment or message after your modification.

Thanks!

2024-07-30 12:03 UTC, miooo0o commented on include/RequestHandler.hpp
> +								Location*>& locations);
함수 위치가 확정이 안되서요. 따로 변경사항 없으면 나중에 member로 넣을거에요.

2024-07-30 12:04 UTC, miooo0o commented on src/server/StaticFileHandler.cpp
> +std::string	genDirListingHtml(const std::string& path)
오 그것도 좋은 생각입니다! 사실 이 함수도 일단은 member로 넣을 이유가 크게 없어서 빼둔건데 계속 유지하는거로 생각할게요!

2024-07-30 12:04 UTC, miooo0o commented on src/server/StaticFileHandler.cpp
> +
확인하고 수정할게요!

2024-07-30 12:04 UTC, miooo0o commented on src/server/StaticFileHandler.cpp
> +		return (_handleNotFound());
이런 치명적인 실수를. 감사합니다, 수정할게요.

2024-07-30 15:26 UTC, san-ghun approved these changes
Thanks for your correction.

2024-07-30 15:26 UTC, merged